vich_uploader:
    db_driver: orm

    mappings:
        attachments:
            uri_prefix: /uploads/memoires
            upload_destination: '%kernel.project_dir%/public/uploads/memoires'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
